#!/usr/bin/env bash
###############################################################################
#Script          :      SIM_TRAN
#
#Purpose         :      Starten der transienten Simulation
#
#Programmer      :      Ralf Putz
#
#History         :      Dezember 1995
#
###############################################################################

#export MODELDIR=$MODELDIR
#export TNETHOME=$TNETHOME

distr="null"
distr_string="null"
method="null"
trans="null"
rule="null"
rule_string="null"
resmon="null"
resmon_string="null"
transient_time="null"
abort_cond="null"
no_sampling_points="null"
maxsamples="null"
maxtime="null"
max_execution_time="null"
nice=4

#############################################################################
# clear files                 
#############################################################################
function clearfiles
{
  \rm -f "$MODEL_ERC.c"
  \rm -f "$MODEL_RDY.c"
  \rm -f "$MODEL_MDF.c"
  \rm -f "$MODEL_RUC.c"
  \rm -f "$MODEL_ERC.o"
  \rm -f "$MODEL_RDY.o"
  \rm -f "$MODEL_MDF.o"
  \rm -f "$MODEL_RUC.o"
  \rm -f "$MODEL.DEFINFO"
  \rm -f "$MODEL_master"
  \rm -f "$MODEL_slave"
  \rm -f "$MODEL.sim_curves"
  \rm -f "$MODEL.temp_sim_curves"
  # $unlock_model "$NAME"

  mkdir -p "$MODEL.dir"

  if [ -e "${MODEL}.pid" ];  then
    mv "$MODEL.pid" "$MODEL.dir"
  fi
  if [ -e "${MODEL}.RESULTS" ];  then
    mv "$MODEL.RESULTS" "$MODEL.dir"
  fi
  if [ -e "${MODEL}.STAT_OUT" ];  then
    mv "$MODEL.STAT_OUT" "$MODEL.dir"
  fi
  if [ -e "${MODEL}.TN" ];  then
    mv "$MODEL.TN" "$MODEL.dir"
  fi
}


usage="Usage : SIM_TRAN model -{D|S} -{Pon|Poff} -{Gon|Goff} <transient_time> <abort_cond> <no_sampling_points> <conf.level> <epsilon> <seed> <max.real time>"

#input netname
if [ $# -lt 1 ]; then
	echo $usage
  exit 1
fi
if [ $# -eq 1 ]; then
 if [ "$1" = "-h" -o "$1" = "-help" ]; then
    echo $usage
    exit 1
 fi
fi

# check environment
if [ "$TNETHOME" = "" ]; then
	echo "Environment variable TNETHOME is not set"
	exit
fi
if [ ! -d "$TNETHOME" ]; then
	echo "Environment variable TNETHOME is not a directory"
	exit
fi
if [ "$MODELDIR" = "" ]; then
	echo "Environment variable MODELDIR is not set"
	exit
fi
if [ ! -d "$MODELDIR" ]; then
	echo "Environment variable MODELDIR is not a directory"
	exit
fi

# set path names
BIN_DIR=${TNETHOME}/EDSPN/Simulation/bin
SIM_DIR=${TNETHOME}/EDSPN/Simulation
SHARED_BIN_DIR=${TNETHOME}/EDSPN/Shared/bin
NAME=$1
MODEL="$MODELDIR/$NAME"

# check net
if [ ! -e "$MODEL.TN" ];  then
     # if only xml-file exists, use xml2tn exporter to create TN-file
     if [ -e "$MODEL.xml" ];  then
        cd "${TNETHOME}/EDSPNGen"
        ./xml2tn.sh "$MODEL.xml"
        cd $currentdir
     else
        echo "No such net"
        echo
        exit -1
     fi
fi

if [ $# -ge 2 ]; then
  distr=$2
else
  distr="-D";
fi

if [ $# -ge 3 ]; then
	rule=$3
else
	rule="-Pon";
fi

if [ $# -ge 4 ]; then
	resmon=$4
else
	resmon="-Gon";
fi

if [ $# -ge 5 ]; then
	transient_time=$5
else
	transient_time="10.0";
fi

if [ $# -ge 6 ]; then
	abort_cond=$6
else
	abort_cond="0";
fi

if [ $# -ge 7 ]; then
	no_sampling_points=$7
else
	no_sampling_points="10";
fi

if [ $# -ge 8 ]; then
	level=$8
else
	level="95";
fi

if [ $# -ge 9 ]; then
	epsilon=$9
else
	epsilon="10";
fi

shift

if [ $# -ge 9 ]; then
	seed=$9
else
	seed="12345";
fi

shift

if [ $# -ge 9 ]; then
	max_execution_time=$9
else
	max_execution_time="0.0";
fi

#Voreinstellungen
trans="Toff"
method="-STR"
#Dummy-Variablen
maxsamples="0";
maxtime="0.0";

case $distr in
  -S)
	   distr_string="Sequential "
	   distr="S"
	   ;;
  -D)
	   distr_string="Parallel "
	   distr="D"
	   ;;
  *)
	   echo $usage
	   exit 1
     ;;
esac

case $rule in
  -Pon)
	   rule_string="on."
	   rule="Pon"
	   ;;
  -Poff)
	   rule_string="off."
	   rule="Poff"
	   ;;
  *)
	   echo $usage
	   exit 1
esac

case $resmon in
  -Gon)
	   resmon_string="on."
	   resmon="Gon"
	   ;;
  -Goff)
	   resmon_string="off."
	   resmon="Goff"
	   ;;
  *)
	   echo $usage
	   exit 1
esac


# $lock_model $NAME

echo $distr_string" transient Simulation of net:" 
echo "$MODEL"

#############################################################################
# marking dependencies, definition of rewardmeasures
#
# execute 'proc_TN'
#############################################################################
"${SHARED_BIN_DIR}/proc_tn" -s -r "RUC($abort_cond);" "$NAME"
if [ $? -ne 0 ]; then
  echo
  echo ERROR STATE $STATUS occurred while PROC_TN execution.
  # $unlock_model $NAME
  echo SOLUTION OF MODEL $NAME FAILED.
  echo
  clearfiles
  exit -1
fi
# echo "proc_tn done."


gcc -I"${SIM_DIR}/include" -I"${SIM_DIR}/sim_utils/include" -O -c -o "${MODEL}_MDF.o" "${MODEL}_MDF.c"
gcc -I"${SIM_DIR}/include" -I"${SIM_DIR}/sim_utils/include" -O -c -o "${MODEL}_ERC.o" "${MODEL}_ERC.c"
gcc -I"${SIM_DIR}/include" -I"${SIM_DIR}/sim_utils/include" -O -c -o "${MODEL}_RDY.o" "${MODEL}_RDY.c"
gcc -I"${SIM_DIR}/include" -I"${SIM_DIR}/sim_utils/include" -O -c -o "${MODEL}_RUC.o" "${MODEL}_RUC.c"

gcc -o "${MODEL}_slave" "${MODEL}_RUC.o" "${MODEL}_MDF.o" "${MODEL}_ERC.o" "${BIN_DIR}/libsim_str_slave_lnx.a" -L"${BIN_DIR}" -lsim_utils_lnx -L"${SHARED_BIN_DIR}" -lsysdep_lnx -lnetio_lnx -lm
gcc -o "${MODEL}_master" "${MODEL}_RDY.o" "${BIN_DIR}/libsim_str_master_lnx.a" -L"${BIN_DIR}" -lsim_utils_lnx -L"${SHARED_BIN_DIR}" -lsysdep_lnx -lnetio_lnx -lm

if [ ! -e "${MODEL}_master" -o ! -e "${MODEL}_slave" ]; then
   echo "Could not build the simulator, for errors see above."
   # $unlock_model $NAME
   clearfiles
   exit 1
fi

# loop experiment configuration for statistical analysis of simulation

#count to calculate avg
loop=0

#remove old avg file, because new lines are appended
if [ -e "${MODEL}.dir/${NAME}.RESULTS_AVG" ];  then
    rm "${MODEL}.dir/${NAME}.RESULTS_AVG"
  fi


#main loop
for i in {0..0}
do
#inc loop and choose random seed
loop=$((loop+1))
#seed=$RANDOM

#simulation
"${MODEL}_master" "$NAME" $level $epsilon $seed $maxsamples $maxtime $max_execution_time $distr $trans $transient_time $no_sampling_points $rule $ $resmon 
if [ $? -ne 0 ]; then
   echo "could not finish main simulation"
   clearfiles
   exit 1
fi

lineNumber=3
arrayNum=0
name=""

#move new results to dir so they can be read
if [ -e "${MODEL}.RESULTS" ];  then
    mv "$MODEL.RESULTS" "$MODEL.dir"
  fi

#read results 
#case 1: first simulation: initiate result array and gather measure names to file
#case 2: add result to array
while IFS= read -r line; do
	if [ $i -eq 0 ]; then
	    tmp=$(echo $line | cut -d' ' -f3)
   		result[$arrayNum]=$(sed -E 's/([+-]?[0-9.]+)[eE]\+?(-?)([0-9]+)/(\1*10^\2\3)/g' <<<"$tmp")
    	currentName=$(echo $line | cut -d' ' -f1)
    	name="$name $currentName"
   	else
   		tmp=$(echo $line | cut -d' ' -f3)
   		tmp=$(sed -E 's/([+-]?[0-9.]+)[eE]\+?(-?)([0-9]+)/(\1*10^\2\3)/g' <<<"$tmp")
   		result[$arrayNum]=$(echo "scale=14 ; ${result[$arrayNum]} + $tmp" | bc)
   	fi
    arrayNum=$((arrayNum+1))
done < <(tail -n "+$lineNumber" "${MODEL}.dir/${NAME}.RESULTS")

#to print names of measures to file
if [ $i -eq 0 ]; then
	echo "$name" >> "${MODEL}.dir/${NAME}.RESULTS_AVG"
fi
#to concatenate avgs to one line
line=""
for a in "${result[@]}"
do
   avg=$(echo "scale= 14 ; $a/$loop" | bc)
   line="$line $avg"
done

#print avgs to file
echo "$line" >> "${MODEL}.dir/${NAME}.RESULTS_AVG"

done

clearfiles
